default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: todo_development
  username: root
  password: password

test:
  <<: *default
  database: todo_test
  username: root
  password: password

production:
  <<: *default
  database: todo_production
  username: root
  password: password