default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: db_development
  username: root
  password: password

test:
  <<: *default
  database: db_test
  username: root
  password: password

production:
  <<: *default
  database: db_production
  username: root
  password: password